### ISSUE TITLE
Numpad keys doesnt work ingame

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2156]
If you set up Numpad keys for actions in the hotkey configuration they don't work ingame. Restarting UH doesn't help, so it looks like the keys aren't recognized.
##

**Comment by LinuxDonald** [comment]
Should be fixed with sdl2.

**Comment by jmdejong** [comment]
I believe that this is still a problem (at least for me on archlinux).
The numpad 5 key fires the `NUM_5` key event in the settings menu (just like the number bar 5 key), but it fires the `KP_5` event in the main game view.
`keyevent.getKey.getValue()` actually gives different (integer) keycodes for in the setting menu and the main game.
Also, related to this, the shift key doesn't work in the main game: on my keyboard pressing shift-= gives `PLUS` in the settings menus, but fires the event for `EQUALS` in the main game.

**Comment by LinuxDonald** [comment]
Maybe an problem with fifechan?

**Comment by helios2000** [comment]
Sure,  the related issue here: https://github.com/fifengine/fifengine/issues/981
Code that needs to be adjusted: [Fife](https://github.com/fifengine/fifengine/blob/master/engine/core/gui/fifechan/fifechanmanager.cpp#L401) and [Fifechan](https://github.com/fifengine/fifechan/blob/master/include/fifechan/key.hpp#L137)
